name: Generate Contribution Snake

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: rushikeshraghatate90
          outputs: |
            dist/github-snake.svg?palette=github
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#00D9FF&color_dots=#161B22,#0E4429,#006D32,#26A641,#39D353
            dist/github-contribution-grid-snake-dark.gif?color_snake=#00D9FF&color_dots=#161B22,#0E4429,#006D32,#26A641,#39D353&color_background=#0D1117

      - name: Publish snake
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
          commit_message: "Update contribution snake"